name: Update Helm Charts
on: workflow_dispatch
jobs:
  chart-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Update charts
        id: update_charts
        run: |
          helm version
          git rev-parse HEAD
          bash chart-sync.sh

      - name: Set environment variables
        run: |
          echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo 'charts_changed<<EOF' >> $GITHUB_ENV
          git status charts --porcelain >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update charts and index
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: chart-update-${{ env.branch_name }}
          delete-branch: true
          title: "Update charts in the ${{ env.branch_name }} branch"
          body: |
            Changelog:
            ${{ env.charts_changed }}
          labels: |
            chart update

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
